name: CIN

on:
  push:
    branches: 
     - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Release APK
      run: |
           ./gradlew assembleRelease
           ls >> add.txt
           ls build >> README.md
    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.gmail.com
          account: ${{ secrets.MAIL_ACCOUNT }}
          password: ${{ secrets.MAIL_PASSWORD }}
          sender: devellany
          from: ${{ secrets.MAIL_ACCOUNT }}
          to: 15760207563@139.com
          subject: mail title.
          body: file://README.md
          contentType: text/html
          attachments: file://add.txt
